### ISSUE TITLE
Unable to view performance metrics in Artifactory 

### ISSUE THREAD

**Issue by umachintala-2** [jfrog/metrics#5]
**Description**: When configured the metrics:enabled:filebeat in the values.yaml file for helm charts installation, we were not able to view the metrics in the Artifactory after navigation to Application → Trends. Clicking on Artifactory Explore Metrics is routing to our wiki page.

**Steps to reproduce**: After creating the cluster with latest Artifactory/Xray, I have enabled the metrics column, however, was not able to view the Artifactory reports as expected. 

**system.yaml** : 

bash-4.4$ cat /opt/jfrog/artifactory/var/etc/system.yaml  
router:
    serviceRegistry:
        insecure: false
shared:
    metrics:
        enabled: true
        filebeat:
            elasticsearch:
                password: password
                url:[ http://insight:8082](http://insight:8082/)
                username: admin
            enabled: true
            log:
                enabled: true
                level: info
    logging:
        consoleLog:
            enabled: false
    extraJavaOpts: >
        -Dartifactory.access.client.max.connections=50 -Dartifactory.async.corePoolSize=16

    database:
        type: postgresql
        url: "jdbc:postgresql://artifactory-postgresql:5432/artifactory"
        host: ""
        driver: org.postgresql.Driver
        username: "artifactory"
artifactory:
    database:
        maxOpenConnections: 80
    tomcat:
        maintenanceConnector:
            port: 8091
        connector:
            maxThreads: 200
            sendReasonPhrase: false
            extraConfig: acceptCount="100"
frontend:
    session:
        timeMinutes: "30"
access:
    database:
        maxOpenConnections: 80
    tomcat:
        connector:
            maxThreads: 50
            sendReasonPhrase: false
            extraConfig: acceptCount="100"
mc:
    enabled: true
    database:
        maxOpenConnections: 10
    idgenerator:
        maxOpenConnections: 2
    tomcat:
        connector:
            maxThreads: 50
            sendReasonPhrase: false
            extraConfig: acceptCount="100"
metadata:
    database:
        maxOpenConnections: 80
jfconnect:
    enabled: true

**Screenshots**: 
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/106963437/172146074-d1519493-00bc-41a3-a5db-350ba8dfb2d7.png">

**Expected behavior**: We should be able to view the metrics of repositories/artifacts on the trends page in Artifactory UI. 

**Versions**:  I have tested in the latest version(s) of Artifactory/Xray. (7.38.10 & 3.48.2).

**Comment by vasukinjfrog** [comment]
Configuration related and no real fix was required. As confirmed by @umachintala-2

**Comment by vasukinjfrog** [comment]
Closing issue
